url: http://copywrongs.eu/
baseurl: 

# Site settings
title: "Save copyright reform"
email: julia.reda-office@europarl.europa.eu
description: "Right now, the EU is debating plans to fix problems with copyright that affect you every day. But a powerful alliance is sabotaging these necessary updates. Will you join us and fight for them?"